services:
  - type: web
    name: paypal-v6-render-demo
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: PAYPAL_ENV
        value: sandbox
      - key: PAYPAL_SANDBOX_CLIENT_ID
        sync: false
      - key: PAYPAL_SANDBOX_CLIENT_SECRET
        sync: false
